openapi: 3.0.1
info:
  description: 日向坂46を題材にしたサンプルAPI
  title: Hinatazaka API
  version: 1.0.0
servers:
- url: https://localhost/api
paths:
  /members/{id}:
    delete:
      description: メンバーの情報を削除する
      operationId: delete-members-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: OK
      tags:
      - hinatazaka
    get:
      description: メンバーの情報を取得する
      operationId: get-member-id
      parameters:
      - description: ID of pet to fetch
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                dummy:
                  value:
                    id: 14
                    name: 小坂菜緒
                    age: 18
              schema:
                $ref: '#/components/schemas/Member'
          description: successful member response
      summary: メンバー情報
      tags:
      - hinatazaka
    put:
      description: メンバーの情報を更新する
      operationId: put-members-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        description: 更新するメンバー情報
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: OK
      tags:
      - hinatazaka
  /discography/{id}:
    get:
      description: ディスコグラフィー情報を取得する
      operationId: get-discography-id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                dummy:
                  value:
                    id: 1
                    title: キュン
                    type: single
              schema:
                $ref: '#/components/schemas/Discography'
          description: successful discography response
      summary: ディスコグラフィー情報
      tags:
      - hinatazaka
  /members:
    get:
      description: 全メンバーの情報を取得する
      operationId: get-members
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Member'
                type: array
          description: OK
      summary: 全メンバー情報
      tags:
      - hinatazaka
    post:
      description: 新しいメンバーを追加する
      operationId: post-members
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Member'
        description: 新しいメンバー情報
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
          description: OK
      tags:
      - hinatazaka
  /member/add: {}
components:
  schemas:
    Member:
      description: メンバー情報
      example:
        name: name
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 0
        age: 6.027456183070403
      properties:
        id:
          description: ID
          format: int64
          type: integer
        name:
          description: 名前
          type: string
        age:
          description: 年齢
          type: number
        created_at:
          description: レコードの作成日時
          format: date-time
          type: string
      required:
      - name
      title: Member
      type: object
    Discography:
      description: ディスコグラフィー情報
      example:
        center_id: 6.027456183070403
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 0.8008281904610115
        title: title
        type: type
      properties:
        id:
          description: ID
          type: number
        title:
          description: タイトル
          type: string
        type:
          description: 種別
          type: string
        center_id:
          description: センターのメンバーID
          type: number
        created_at:
          description: レコードの作成日時
          format: date-time
          type: string
      required:
      - title
      title: Discography
      type: object
