name: Test

on:
  push:
    branches:
      - master
      - patch-release
  pull_request:

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.3

      - name: Install Dependencies
        working-directory: ./react
        run: npm i

      - name: Test Jest
        working-directory: ./react
        run: npm run test
